=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/queries/query.dtd
<!--
==========================================================================
 This is the DTD for phpLDAPAdmin Queries.

 Copyright (c) 2011

 Temporary URI for the DTD: http://phpldapadmin.sf.net/release/templates/query.dtd
 Validate your templates here: http://www.xmlvalidation.com
==========================================================================
-->

<!-- Query Definition -->
<!ELEMENT query (title,bases,filter,description,icon?,scope,visible?,attributes)>

<!-- Bases Definition -->
<!ELEMENT bases (base*)>

<!-- Attributes Definition -->
<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute (display?,order?,ordersort?)?>
<!ATTLIST attribute id CDATA #REQUIRED>

<!-- Header Parameters -->
<!ELEMENT base (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT filter (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT icon (#PCDATA)>
<!ELEMENT scope (#PCDATA)>
<!ELEMENT visible (#PCDATA)>

<!-- Attribute Parameters -->
<!ELEMENT display (#PCDATA)>
<!ELEMENT order (#PCDATA)>
<!ELEMENT ordersort (#PCDATA)>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/queries/SambaUsers.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE query SYSTEM "query.dtd">

<query>
<title>Samba User List</title>
<bases>
	<base></base>
</bases>
<filter><![CDATA[(&(|(objectClass=sambaAccount)(objectClass=sambaSamAccount))(objectClass=posixAccount)(!(uid=*$)))]]></filter>
<description>Samba Users</description>
<icon>ldap-user.png</icon>
<scope>sub</scope>
<visible>1</visible>

<attributes>
<attribute id="cn">
	<display>Common Name</display>
	<order>1</order>
	<ordersort>2</ordersort>
</attribute>
<attribute id="uid">
	<display>User ID</display>
	<order>2</order>
	<ordersort>1</ordersort>
</attribute>
<attribute id="sambaHomeDrive">
	<display>Samba Home Directory</display>
	<order>3</order>
	<ordersort>3</ordersort>
</attribute>
</attributes>
</query>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/queries/UserList.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE query SYSTEM "query.dtd">

<query>
<title>User List</title>
<bases>
	<base></base>
</bases>
<filter><![CDATA[(&(objectClass=posixAccount)(uid=*))]]></filter>
<description>User List</description>
<icon>ldap-user.png</icon>
<scope>sub</scope>
<visible>1</visible>

<attributes>
<attribute id="cn">
	<display>Common Name</display>
	<order>1</order>
	<ordersort>2</ordersort>
</attribute>
<attribute id="uid">
	<display>User ID</display>
	<order>2</order>
	<ordersort>1</ordersort>
</attribute>
<attribute id="homeDirectory">
	<display>Home Directory</display>
	<order>3</order>
	<ordersort>3</ordersort>
</attribute>
<attribute id="telephoneNumber">
	<display>Telephone Number</display>
	<order>4</order>
	<ordersort>4</ordersort>
</attribute>
<attribute id="jPegPhoto">
	<display>Photo</display>
	<order>5</order>
	<ordersort>5</ordersort>
</attribute>
</attributes>
</query>
