=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/template.dtd
<!--
==========================================================================
 This is the DTD for phpLDAPAdmin Templates.

 Copyright (c) 2009

 Temporary URI for the DTD: http://phpldapadmin.sf.net/release/templates/template.dtd
 Validate your templates here: http://www.xmlvalidation.com
==========================================================================
-->

<!-- Unused -->
<!ENTITY % Boolean "(0 | 1)">

<!-- ================================================================ -->

<!-- Template Definition -->
<!ELEMENT template (askcontainer?,description?,icon?,invalid?,rdn?,regexp?,
	title,visible?,objectClasses,attributes)>

<!-- ObjectClasses Definition -->
<!ELEMENT objectClasses (objectClass+)>
<!ELEMENT objectClass EMPTY>
<!ATTLIST objectClass id CDATA #REQUIRED>

<!-- Attributes Definition -->
<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute (cols?,default?,display?,helper?,hidden?,hint?,icon?,
	maxlength?,onchange*,order?,page?,post?,presubmit?,readonly?,rows?,size?,
	spacer?,type?,value*,verify?)?>
<!ATTLIST attribute id CDATA #REQUIRED>

<!-- helper -->
<!ELEMENT helper (default?,display?,id?,value*)>

<!-- ================================================================ -->

<!-- Common Parameters -->
<!ELEMENT icon (#PCDATA)>
<!ELEMENT default (#PCDATA)>
<!ELEMENT display (#PCDATA)>
<!ELEMENT value (#PCDATA)>

<!-- Header Parameters -->
<!ELEMENT askcontainer (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT invalid (#PCDATA)>
<!ELEMENT rdn (#PCDATA)>
<!ELEMENT regexp (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT visible (#PCDATA)>

<!-- Attribute Parameters -->
<!ELEMENT cols (#PCDATA)>
<!ELEMENT hidden (#PCDATA)>
<!ELEMENT hint (#PCDATA)>
<!ELEMENT maxlength (#PCDATA)>
<!ELEMENT onchange (#PCDATA)>
<!ELEMENT order (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT post (#PCDATA)>
<!ELEMENT presubmit (#PCDATA)>
<!ELEMENT readonly (#PCDATA)>
<!ELEMENT rows (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT spacer (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT verify (#PCDATA)>

<!-- Helper Parameters -->
<!ELEMENT id (#PCDATA)>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/alias.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<template>
<askcontainer>1</askcontainer>
<description>New LDAP Alias</description>
<icon>ldap-alias.png</icon>
<invalid>0</invalid>
<rdn>uid</rdn>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<title>Generic: LDAP Alias</title>
<visible>1</visible>

<objectClasses>
<objectClass id="alias"></objectClass>
<objectClass id="extensibleObject"></objectClass>
</objectClasses>

<attributes>
<attribute id="aliasedObjectName">
	<display>Alias To</display>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="uid">
	<display>User ID</display>
	<order>1</order>
	<page>1</page>
</attribute>
</attributes>

</template>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/sendmailVirtualUser.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<!--This template doesnt does not appear to be correct. If it is correct, or if
    you have modifications to make it correct, then let us know, and we'll
    update and enable it.-->

<template>
<askcontainer>1</askcontainer>
<description>New Sendmail Virtual User</description>
<icon>mail.png</icon>
<invalid>1</invalid>
<rdn>sendmailMTAMapObject</rdn>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<title>Sendmail: Virtual Users</title>
<visible>1</visible>

<objectClasses>
<objectClass id="sendmailMTAMapObject"></objectClass>
</objectClasses>

<attributes>
<attribute id="sendmailMTACluster">
	<display>Sendmail Cluster Name</display>
	<icon>ldap-default.png</icon>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAHost">
	<display>Sendmail Hostname</display>
	<hint>Leave Blank</hint>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAKey">
	<display>Email alias</display>
	<hint>use @example.com to map entire domain</hint>
	<order>3</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAMapValue">
	<display>Recipient Addresses</display>
	<hint>use %1 to map user name port of address</hint>
	<order>4</order>
	<page>1</page>
	<type>textarea</type>
</attribute>
<attribute id="sendmailMTAMapName">
	<hidden>1</hidden>
	<value>virtuser</value>
</attribute>
</attributes>

</template>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/sambaGroupMapping.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<template>
<askcontainer>1</askcontainer>
<description>New Samba3 Group Mapping</description>
<icon>ldap-ou.png</icon>
<invalid>0</invalid>
<rdn>cn</rdn>
<!-- <regexp>^ou=.*,</regexp> -->
<title>Samba: Group Mapping</title>
<visible>1</visible>

<objectClasses>
<objectClass id="posixGroup"></objectClass>
<objectClass id="sambaGroupMapping"></objectClass>
</objectClasses>

<attributes>
<attribute id="cn">
	<display>Group</display>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="displayName">
	<display>Windows Name</display>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="gidNumber">
	<display>GID Number</display>
	<order>3</order>
	<page>1</page>
	<readonly>1</readonly>
	<spacer>1</spacer>
	<value><![CDATA[=php.GetNextNumber(/;gidNumber;true;(&(objectClass=sambaDomain)(sambaDomainName=mysambadomain))]]></value>
</attribute>
<attribute id="sambaSID">
	<display>Samba SID</display>
	<helper>
		<id>sidsuffix</id>
		<value><![CDATA[=php.GetNextNumber(/;gidNumber;false;(&(objectClass=sambaDomain)(sambaDomainName=mysambadomain));*2,+1000)]]></value>
	</helper>
	<order>4</order>
	<post>=php.Join(-;%sambaSID%,%sidsuffix%)</post>
	<page>1</page>
	<value><![CDATA[=php.PickList(/;(&(objectClass=sambaDomain));sambaSID;%sambaSID% (%sambaDomainName%);;;;sambaDomainName)]]></value>
</attribute>
<attribute id="sambaGroupType">
	<display>Samba Group Type</display>
	<order>5</order>
	<page>1</page>
	<spacer>1</spacer>
	<type>select</type>
	<value id="2">Domain Group</value>
	<value id="4">Local Group</value>
	<value id="5">Well-known Group</value>
</attribute>
<attribute id="memberUid">
	<display>Users</display>
	<hidden>0</hidden>
	<order>10</order>
	<page>1</page>
	<size>10</size>
	<value><![CDATA[=php.MultiList(/;(&(objectClass=posixAccount));uid)]]></value>
	<!-- <value><![CDATA[=php.MultiList(/;(&(objectClass=posixAccount));uid;%cn% %uid|-4/U%;memberUid;dmdName=users,dc=localdomain;root => cn=root, nobody => cn=nobody;cn;;;)]]></value> -->
</attribute>
</attributes>

</template>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/inetOrgPerson.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<template>
<askcontainer>1</askcontainer>
<description>New Address Book Entry</description>
<icon>address-book.png</icon>
<invalid>0</invalid>
<rdn>cn</rdn>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<title>Generic: Address Book Entry</title>
<visible>1</visible>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
</objectClasses>

<attributes>
<attribute id="givenName">
	<display>First name</display>
	<icon>ldap-uid.png</icon>
	<onchange>=autoFill(cn;%givenName% %sn%)</onchange>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sn">
	<display>Last name</display>
	<onchange>=autoFill(cn;%givenName% %sn%)</onchange>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="cn">
	<display>Common Name</display>
	<order>3</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="jpegPhoto">
	<display>Photo</display>
	<order>3</order>
	<spacer>1</spacer>
</attribute>
<attribute id="o">
	<display>Organisation</display>
	<order>4</order>
	<page>1</page>
</attribute>
<attribute id="street">
	<cols>50</cols>
	<display>Street</display>
	<icon>mail.png</icon>
	<order>4</order>
	<page>1</page>
	<rows>4</rows>
	<type>textarea</type>
</attribute>
<attribute id="l">
	<display>City</display>
	<order>5</order>
	<page>1</page>
</attribute>
<attribute id="st">
	<display>State</display>
	<order>6</order>
	<page>1</page>
</attribute>
<attribute id="postalCode">
	<display>Postal code</display>
	<order>7</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="telephoneNumber">
	<display>Work phone</display>
	<icon>phone.png</icon>
	<order>8</order>
	<page>1</page>
</attribute>
<attribute id="facsimileTelephoneNumber">
	<display>Fax</display>
	<order>9</order>
	<page>1</page>
</attribute>
<attribute id="mobile">
	<display>Mobile</display>
	<order>9</order>
	<page>1</page>
</attribute>
<attribute id="mail">
	<display>Email</display>
	<order>10</order>
	<page>1</page>
</attribute>
</attributes>

</template>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/sambaDomain.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<template>
<askcontainer>1</askcontainer>
<description>New Samba Domain</description>
<icon>ldap-dc.png</icon>
<invalid>0</invalid>
<rdn>sambaDomainName</rdn>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<title>Samba: Domain</title>
<visible>1</visible>

<objectClasses>
<objectClass id="sambaDomain"></objectClass>
</objectClasses>

<attributes>
<attribute id="sambaDomainName">
	<display>Samba Domain Name</display>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sambaSID">
	<display>Samba SID</display>
	<hint>Samba SID is in the format S-1-5-21-x-y-z</hint>
	<order>2</order>
	<page>1</page>
	<value>S-1-5-21-</value>
</attribute>
</attributes>

</template>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/modification/inetOrgPerson.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<template>
<description>Address Book Entry</description>
<icon>address-book.png</icon>
<invalid>0</invalid>
<rdn>cn</rdn>
<noleaf>1</noleaf>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<title>Generic: Address Book Entry</title>
<visible>0</visible>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
</objectClasses>

<attributes>
<attribute id="givenName">
	<display>First name</display>
	<icon>ldap-uid.png</icon>
	<onchange>=autoFill(cn;%givenName% %sn%)</onchange>
	<order>1</order>
</attribute>
<attribute id="sn">
	<display>Last name</display>
	<onchange>=autoFill(cn;%givenName% %sn%)</onchange>
	<order>2</order>
</attribute>
<attribute id="cn">
	<display>Common Name</display>
	<order>3</order>
	<readonly>1</readonly>
	<spacer>1</spacer>
</attribute>
<attribute id="jpegPhoto">
	<display>Photo</display>
	<order>3</order>
	<spacer>1</spacer>
</attribute>
<attribute id="o">
	<display>Organisation</display>
	<order>4</order>
</attribute>
<attribute id="street">
	<cols>50</cols>
	<display>Street</display>
	<icon>mail.png</icon>
	<order>5</order>
	<rows>4</rows>
	<type>textarea</type>
</attribute>
<attribute id="l">
	<display>City</display>
	<order>6</order>
</attribute>
<attribute id="st">
	<display>State</display>
	<order>7</order>
</attribute>
<attribute id="postalCode">
	<display>Postal code</display>
	<order>8</order>
	<spacer>1</spacer>
</attribute>
<attribute id="telephoneNumber">
	<display>Work phone</display>
	<icon>phone.png</icon>
	<order>9</order>
</attribute>
<attribute id="facsimileTelephoneNumber">
	<display>Fax</display>
	<order>10</order>
</attribute>
<attribute id="mobile">
	<display>Mobile</display>
	<order>11</order>
</attribute>
<attribute id="mail">
	<display>Email</display>
	<order>12</order>
</attribute>
</attributes>

</template>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/modification/posixGroup.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<template>
<askcontainer>1</askcontainer>
<description>New Posix Group</description>
<icon>ldap-ou.png</icon>
<invalid>0</invalid>
<noleaf>1</noleaf>
<rdn>cn</rdn>
<!-- <regexp>^ou=.*,</regexp> -->
<title>Generic: Posix Group</title>
<visible>0</visible>

<objectClasses>
<objectClass id="posixGroup"></objectClass>
</objectClasses>

<attributes>
<attribute id="cn">
	<display>Group</display>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="gidNumber">
	<display>GID Number</display>
	<!-- <option><![CDATA[=php.GetNextNumber(/;gidNumber;false;(&(objectClass=posixGroup));*2,+1000)]]></option> -->
	<order>2</order>
	<page>1</page>
	<readonly>1</readonly>
	<spacer>1</spacer>
	<value>=php.GetNextNumber(/;gidNumber)</value>
</attribute>
<attribute id="memberUid">
	<display>Users</display>
	<hidden>0</hidden>
	<order>3</order>
	<page>1</page>
	<value><![CDATA[=php.MultiList(/;(objectClass=posixAccount);uid;%cn% (%uid|-4%))]]></value>
</attribute>
</attributes>

</template>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/sendmailMTAMapObject.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<!--This template doesnt does not appear to be correct. If it is correct, or if
    you have modifications to make it correct, then let us know, and we'll
    update and enable it.-->

<template>
<askcontainer>1</askcontainer>
<description>New Sendmail Relays</description>
<icon>mail.png</icon>
<invalid>1</invalid>
<rdn>sendmailMTACluster</rdn>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<title>Sendmail: Relays</title>
<visible>1</visible>

<objectClasses>
<objectClass id="sendmailMTAMapObject"></objectClass>
</objectClasses>

<attributes>
<attribute id="sendmailMTACluster">
	<display>Sendmail Cluster Name</display>
	<icon>ldap-default.png</icon>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAHost">
	<display>Sendmail Hostname</display>
	<hint>Leave Blank</hint>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAKey">
	<display>Host/Network/Address</display>
	<order>3</order>
	<page>1</page>
	<type>select</type>
	<value id="RELAY">RELAY: Allow host/network/address to relay</value>
	<value id="OK">OK: Accept local mail but disallow relay</value>
	<value id="REJECT">REJECT: Reject messages</value>
	<value id="DISCARD">DISCARD: Discard messages</value>
	<value id="SKIP">SKIP: Apply default action to messages</value>
	<value id="ERROR">ERROR: Reject message with custom error</value>
</attribute>
<attribute id="sendmailMTAMapName">
	<hidden>1</hidden>
	<value>access</value>
</attribute>
</attributes>

</template>
