=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/template.dtd
<!--
==========================================================================
 This is the DTD for phpLDAPAdmin Templates.

 Copyright (c) 2009

 Temporary URI for the DTD: http://phpldapadmin.sf.net/release/templates/template.dtd
 Validate your templates here: http://www.xmlvalidation.com
==========================================================================
-->

<!-- Unused -->
<!ENTITY % Boolean "(0 | 1)">

<!-- ================================================================ -->

<!-- Template Definition -->
<!ELEMENT template (askcontainer?,description?,icon?,invalid?,rdn?,regexp?,
	title,visible?,objectClasses,attributes)>

<!-- ObjectClasses Definition -->
<!ELEMENT objectClasses (objectClass+)>
<!ELEMENT objectClass EMPTY>
<!ATTLIST objectClass id CDATA #REQUIRED>

<!-- Attributes Definition -->
<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute (cols?,default?,display?,helper?,hidden?,hint?,icon?,
	maxlength?,onchange*,order?,page?,post?,presubmit?,readonly?,rows?,size?,
	spacer?,type?,value*,verify?)?>
<!ATTLIST attribute id CDATA #REQUIRED>

<!-- helper -->
<!ELEMENT helper (default?,display?,id?,value*)>

<!-- ================================================================ -->

<!-- Common Parameters -->
<!ELEMENT icon (#PCDATA)>
<!ELEMENT default (#PCDATA)>
<!ELEMENT display (#PCDATA)>
<!ELEMENT value (#PCDATA)>

<!-- Header Parameters -->
<!ELEMENT askcontainer (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT invalid (#PCDATA)>
<!ELEMENT rdn (#PCDATA)>
<!ELEMENT regexp (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT visible (#PCDATA)>

<!-- Attribute Parameters -->
<!ELEMENT cols (#PCDATA)>
<!ELEMENT hidden (#PCDATA)>
<!ELEMENT hint (#PCDATA)>
<!ELEMENT maxlength (#PCDATA)>
<!ELEMENT onchange (#PCDATA)>
<!ELEMENT order (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT post (#PCDATA)>
<!ELEMENT presubmit (#PCDATA)>
<!ELEMENT readonly (#PCDATA)>
<!ELEMENT rows (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT spacer (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT verify (#PCDATA)>

<!-- Helper Parameters -->
<!ELEMENT id (#PCDATA)>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/dNSDomain.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<template>
<askcontainer>1</askcontainer>
<description>New DNS Entry</description>
<icon>ldap-dc.png</icon>
<invalid>0</invalid>
<rdn>dc</rdn>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<title>Generic: DNS Entry</title>
<visible>1</visible>

<objectClasses>
<objectClass id="dnsDomain"></objectClass>
<objectClass id="domainRelatedObject"></objectClass>
</objectClasses>

<attributes>
<attribute id="dc">
	<display>Domain Component</display>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="associatedDomain">
	<display>Associated Domain</display>
	<order>2</order>
	<page>1</page>
</attribute>
</attributes>

</template>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/simpleSecurityObject.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<template>
<askcontainer>1</askcontainer>
<description>New Simple Security Object</description>
<icon>ldap-user.png</icon>
<invalid>0</invalid>
<rdn>userid</rdn>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<title>Generic: Simple Security Object</title>
<visible>1</visible>

<objectClasses>
<objectClass id="account"></objectClass>
<objectClass id="simpleSecurityObject"></objectClass>
</objectClasses>

<attributes>
<attribute id="userid">
	<display>User Name</display>
	<icon>ldap-uid.png</icon>
	<order>1</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="userPassword">
	<display>Password</display>
	<icon>lock.png</icon>
	<order>5</order>
	<page>1</page>
	<post>=php.PasswordEncrypt(%enc%;%userPassword%)</post>
	<verify>1</verify>
</attribute>
</attributes>

</template>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/kolabPerson.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<template>
<askcontainer>1</askcontainer>
<description>New Address Book Entry</description>
<icon>address-book.png</icon>
<invalid>0</invalid>
<rdn>cn</rdn>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<title>Kolab: User Entry</title>
<visible>1</visible>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
</objectClasses>

<attributes>
<attribute id="givenName">
	<display>First name</display>
	<icon>ldap-uid.png</icon>
	<onchange>=autoFill(cn;%givenName% %sn%)</onchange>
	<order>1</order>
</attribute>
<attribute id="sn">
	<display>Last name</display>
	<onchange>=autoFill(cn;%givenName% %sn%)</onchange>
	<order>2</order>
</attribute>
<attribute id="cn">
	<display>Common Name</display>
	<order>3</order>
</attribute>
<attribute id="mail">
	<display>Email</display>
	<order>4</order>
</attribute>
<attribute id="userPassword">
	<display>Password</display>
	<icon>lock.png</icon>
	<order>5</order>
	<post>=php.PasswordEncrypt(%enc%;%userPassword%)</post>
	<spacer>1</spacer>
	<verify>1</verify>
</attribute>
<attribute id="title">
	<display>Title</display>
	<icon>ldap-ou.png</icon>
	<order>6</order>
</attribute>
<attribute id="alias">
	<display>Alias</display>
	<order>7</order>
</attribute>
<attribute id="o">
	<display>Organisation</display>
	<order>8</order>
</attribute>
<attribute id="ou">
	<display>Organisational unit</display>
	<order>9</order>
</attribute>
<attribute id="roomNumber">
	<display>Room Number</display>
	<order>10</order>
	<spacer>1</spacer>
</attribute>
<attribute id="street">
	<display>Address</display>
	<icon>mail.png</icon>
	<order>11</order>
</attribute>
<attribute id="postOfficeBox">
	<display>Post box</display>
	<order>12</order>
</attribute>
<attribute id="l">
	<display>City</display>
	<order>13</order>
</attribute>
<attribute id="st">
	<display>State</display>
	<order>14</order>
</attribute>
<attribute id="postalCode">
	<display>Postal code</display>
	<order>15</order>
</attribute>
<!-- <attribute id="c">
	<display>Country</display>
	<order>16</order>
	<spacer>1</spacer>
</attribute> -->
<attribute id="telephoneNumber">
	<display>Work phone</display>
	<icon>phone.png</icon>
	<order>17</order>
</attribute>
<attribute id="facsimileTelephoneNumber">
	<display>Fax</display>
	<order>18</order>
</attribute>
<attribute id="mobile">
	<display>Mobile</display>
	<order>19</order>
</attribute>
</attributes>

</template>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/posixAccount.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "../template.dtd">

<template>
<askcontainer>1</askcontainer>
<description>New User Account</description>
<icon>ldap-user.png</icon>
<invalid>0</invalid>
<rdn>cn</rdn>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<title>Generic: User Account</title>
<visible>1</visible>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
<objectClass id="posixAccount"></objectClass>
</objectClasses>

<attributes>
<attribute id="givenName">
	<display>First name</display>
	<icon>ldap-uid.png</icon>
	<onchange>=autoFill(cn;%givenName% %sn%)</onchange>
	<onchange>=autoFill(uid;%givenName|0-1/l%%sn/l%)</onchange>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sn">
	<display>Last name</display>
	<onchange>=autoFill(cn;%givenName% %sn%)</onchange>
	<onchange>=autoFill(uid;%givenName|0-1/l%%sn/l%)</onchange>
	<!-- <onchange>=autoFill(homeDirectory;/home/users/%uid|0-1/l%/%uid%)</onchange> -->
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="cn">
	<display>Common Name</display>
	<order>3</order>
	<page>1</page>
</attribute>
<attribute id="uid">
	<display>User ID</display>
	<onchange>=autoFill(homeDirectory;/home/users/%uid%)</onchange>
	<order>4</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="homeDirectory">
	<display>Home directory</display>
	<!-- <onchange>=autoFill(homeDirectory;/home/users/%gidNumber|0-0/T%/%uid|3-%)</onchange> -->
	<order>8</order>
	<page>1</page>
</attribute>
<attribute id="uidNumber">
	<display>UID Number</display>
	<icon>terminal.png</icon>
	<order>6</order>
	<page>1</page>
	<readonly>1</readonly>
	<value>=php.GetNextNumber(/;uidNumber)</value>
</attribute>
<attribute id="gidNumber">
	<display>GID Number</display>
	<!-- <onchange>=autoFill(homeDirectory;/home/users/%gidNumber|0-0/T%/%uid|3-%)</onchange> -->
	<order>7</order>
	<page>1</page>
	<value><![CDATA[=php.PickList(/;(&(objectClass=posixGroup));gidNumber;%cn%;;;;cn)]]></value>
</attribute>
<attribute id="loginShell">
	<display>Login shell</display>
	<order>9</order>
	<page>1</page>
	<!-- <value><![CDATA[=php.PickList(/;(&(objectClass=posixAccount));loginShell;%loginShell%;;;;loginShell)]]></value> -->
	<type>select</type>
	<value id="/bin/sh">Bash</value>
	<value id="/bin/csh">C Shell</value>
	<value id="/bin/tsh">Turbo C Shell</value>
</attribute>
<attribute id="userPassword">
	<display>Password</display>
	<!-- <helper>
		<display>Encryption</display>
		<id>enc</id>
		<value>=php.PasswordEncryptionTypes()</value>
	</helper> -->
	<icon>lock.png</icon>
	<order>5</order>
	<page>1</page>
	<post>=php.PasswordEncrypt(%enc%;%userPassword%)</post>
	<spacer>1</spacer>
	<verify>1</verify>
</attribute>
</attributes>

</template>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/sendmailMTAAliasObject.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<template>
<askcontainer>1</askcontainer>
<description>New Sendmail Alias</description>
<icon>mail.png</icon>
<invalid>0</invalid>
<rdn>sendmailMTACluster</rdn>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<title>Sendmail: Alias</title>
<visible>1</visible>

<objectClasses>
<objectClass id="sendmailMTAAliasObject"></objectClass>
</objectClasses>

<attributes>
<attribute id="sendmailMTACluster">
	<display>Sendmail Cluster Name</display>
	<icon>ldap-default.png</icon>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAHost">
	<display>Sendmail Hostname</display>
	<hint>Leave Blank</hint>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAKey">
	<display>Email alias</display>
	<order>3</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAAliasValue">
	<display>Recipient Addresses</display>
	<order>4</order>
	<page>1</page>
	<type>textarea</type>
</attribute>
<attribute id="sendmailMTAAliasGrouping">
	<hidden>1</hidden>
	<value>aliases</value>
</attribute>
</attributes>

</template>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/sendmailMTACluster.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<template>
<askcontainer>1</askcontainer>
<description>New Sendmail Cluster</description>
<icon>mail.png</icon>
<invalid>0</invalid>
<rdn>sendmailMTACluster</rdn>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<title>Sendmail: Cluster</title>
<visible>1</visible>

<objectClasses>
<objectClass id="sendmailMTA"></objectClass>
</objectClasses>

<attributes>
<attribute id="sendmailMTACluster">
	<display>Alias To</display>
	<order>1</order>
	<page>1</page>
</attribute>
</attributes>

</template>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/sambaMachine.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<template>
<askcontainer>1</askcontainer>
<description>New Samba3 Machine</description>
<icon>server.png</icon>
<invalid>0</invalid>
<rdn>uid</rdn>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<title>Samba: Machine</title>
<visible>1</visible>

<objectClasses>
<objectClass id="sambaSAMAccount"></objectClass>
<objectClass id="posixAccount"></objectClass>
<objectClass id="account"></objectClass>
</objectClasses>

<attributes>
<attribute id="uid">
	<display>Machine Name</display>
	<hint>The machine name should end with a $</hint>
	<icon>terminal.png</icon>
	<onchange>=autoFill(cn;%uid%)</onchange>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="uidNumber">
	<display>UID Number</display>
	<order>2</order>
	<page>1</page>
	<readonly>1</readonly>
	<value>=php.GetNextNumber(/;uidNumber)</value>
</attribute>
<attribute id="gidNumber">
	<display>GID Number</display>
	<order>3</order>
	<page>1</page>
	<value><![CDATA[=php.PickList(/;(&(objectClass=posixGroup));gidNumber;%cn%;;;;cn)]]></value>
</attribute>
<attribute id="sambaSID">
	<display>Samba SID</display>
	<helper>
		<id>sidsuffix</id>
		<value></value>
	</helper>
	<order>2</order>
	<page>1</page>
	<post>=php.Join(-;%sambaSID%,%sidsuffix%)</post>
	<value><![CDATA[=php.PickList(/;(&(objectClass=sambaDomain));sambaSID;%sambaSID% (%sambaDomainName%);;;;sambaDomainName)]]></value>
</attribute>
<attribute id="sambaAcctFlags">
	<hidden>1</hidden>
	<value>[W]</value>
</attribute>
<attribute id="homeDirectory">
	<hidden>1</hidden>
	<value>/dev/null</value>
</attribute>
<attribute id="cn">
	<hidden>1</hidden>
	<value></value>
</attribute>
</attributes>

</template>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/organizationalRole.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<template>
<askcontainer>1</askcontainer>
<description>New Organisational Role</description>
<icon>ldap-o.png</icon>
<invalid>0</invalid>
<rdn>cn</rdn>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<title>Generic: Organisational Role</title>
<visible>1</visible>

<objectClasses>
<objectClass id="organizationalRole"></objectClass>
</objectClasses>

<attributes>
<attribute id="cn">
	<display>Role CN</display>
	<order>1</order>
	<spacer>1</spacer>
</attribute>
<attribute id="telephoneNumber">
	<display>Work phone</display>
	<icon>phone.png</icon>
	<order>2</order>
</attribute>
<attribute id="facsimileTelephoneNumber">
	<display>Fax</display>
	<order>3</order>
	<spacer>1</spacer>
</attribute>
<attribute id="description">
	<display>Comments</display>
	<icon>light.png</icon>
	<order>4</order>
	<spacer>1</spacer>
</attribute>
<attribute id="roleOccupant">
	<display>Occupant</display>
	<icon>ldap-default.png</icon>
	<order>5</order>
	<spacer>1</spacer>
</attribute>
<attribute id="street">
	<display>Street Address</display>
	<icon>mail.png</icon>
	<order>6</order>
</attribute>
<attribute id="l">
	<display>City</display>
	<order>7</order>
</attribute>
<attribute id="st">
	<display>State</display>
	<order>8</order>
</attribute>
<attribute id="postalCode">
	<display>Postal code</display>
	<order>9</order>
	<spacer>1</spacer>
</attribute>
<attribute id="postalAddress">
	<display>Postal Address</display>
	<icon>mail.png</icon>
	<order>10</order>
	<spacer>1</spacer>
</attribute>
<attribute id="registeredAddress">
	<display>Registered Address</display>
	<icon>mail.png</icon>
	<order>11</order>
</attribute>
</attributes>

</template>
