=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/template.dtd
<!--
==========================================================================
 This is the DTD for phpLDAPAdmin Templates.

 Copyright (c) 2009

 Temporary URI for the DTD: http://phpldapadmin.sf.net/release/templates/template.dtd
 Validate your templates here: http://www.xmlvalidation.com
==========================================================================
-->

<!-- Unused -->
<!ENTITY % Boolean "(0 | 1)">

<!-- ================================================================ -->

<!-- Template Definition -->
<!ELEMENT template (askcontainer?,description?,icon?,invalid?,rdn?,regexp?,
	title,visible?,objectClasses,attributes)>

<!-- ObjectClasses Definition -->
<!ELEMENT objectClasses (objectClass+)>
<!ELEMENT objectClass EMPTY>
<!ATTLIST objectClass id CDATA #REQUIRED>

<!-- Attributes Definition -->
<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute (cols?,default?,display?,helper?,hidden?,hint?,icon?,
	maxlength?,onchange*,order?,page?,post?,presubmit?,readonly?,rows?,size?,
	spacer?,type?,value*,verify?)?>
<!ATTLIST attribute id CDATA #REQUIRED>

<!-- helper -->
<!ELEMENT helper (default?,display?,id?,value*)>

<!-- ================================================================ -->

<!-- Common Parameters -->
<!ELEMENT icon (#PCDATA)>
<!ELEMENT default (#PCDATA)>
<!ELEMENT display (#PCDATA)>
<!ELEMENT value (#PCDATA)>

<!-- Header Parameters -->
<!ELEMENT askcontainer (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT invalid (#PCDATA)>
<!ELEMENT rdn (#PCDATA)>
<!ELEMENT regexp (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT visible (#PCDATA)>

<!-- Attribute Parameters -->
<!ELEMENT cols (#PCDATA)>
<!ELEMENT hidden (#PCDATA)>
<!ELEMENT hint (#PCDATA)>
<!ELEMENT maxlength (#PCDATA)>
<!ELEMENT onchange (#PCDATA)>
<!ELEMENT order (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT post (#PCDATA)>
<!ELEMENT presubmit (#PCDATA)>
<!ELEMENT readonly (#PCDATA)>
<!ELEMENT rows (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT spacer (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT verify (#PCDATA)>

<!-- Helper Parameters -->
<!ELEMENT id (#PCDATA)>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/example.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<template>
<askcontainer>1</askcontainer>
<description>This is the description</description>
<icon>star.png</icon>
<invalid>1</invalid>
<rdn>o</rdn>
<regexp>^$</regexp>
<title>Example entry</title>
<visible>0</visible>

<objectClasses>
<objectClass id="organization"></objectClass>
</objectClasses>

<attributes>
<attribute id="attribute1">
	<display>Attribute 1</display>
	<hint>This is an example</hint>
	<icon>ldap-uid.png</icon>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="attribute2">
	<display>Attribute 2</display>
	<order>2</order>
	<page>2</page>
</attribute>
<attribute id="attribute3">
	<display>Attribute 3</display>
	<order>1</order>
	<page>2</page>
</attribute>
</attributes>

</template>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/sendmailMTAClass.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<template>
<askcontainer>1</askcontainer>
<description>New Sendmail Domain</description>
<icon>mail.png</icon>
<invalid>0</invalid>
<rdn>sendmailMTACluster</rdn>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<title>Sendmail: Domain</title>
<visible>1</visible>

<objectClasses>
<objectClass id="sendmailMTAClass"></objectClass>
</objectClasses>

<attributes>
<attribute id="sendmailMTACluster">
	<display>Sendmail Cluster Name</display>
	<icon>ldap-default.png</icon>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAHost">
	<display>Sendmail Hostname</display>
	<hint>Leave Blank</hint>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAClassValue">
	<display>Email domain</display>
	<order>3</order>
	<page>1</page>
</attribute>
<attribute id="sendmailMTAClassName">
	<hidden>1</hidden>
	<value>w</value>
</attribute>
</attributes>

</template>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/courierMailAlias.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<template>
<askcontainer>1</askcontainer>
<description>New Courier Mail Alias</description>
<icon>mail_alias.png</icon>
<invalid>0</invalid>
<rdn>cn</rdn>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<title>Courier Mail: Alias</title>
<visible>1</visible>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
<objectClass id="courierMailAlias"></objectClass>
</objectClasses>

<attributes>
<attribute id="cn">
	<display>Common Name</display>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sn">
	<display>Last name</display>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="mail">
	<display>Email</display>
	<order>3</order>
	<page>1</page>
</attribute>
<attribute id="maildrop">
	<display>Maildrop</display>
	<order>4</order>
	<page>1</page>
</attribute>
</attributes>

</template>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/mozillaOrgPerson.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<template>
<askcontainer>1</askcontainer>
<description>New Thunderbird Address Book Entry</description>
<icon>address-book.png</icon>
<invalid>0</invalid>
<rdn>cn</rdn>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<title>Thunderbird: Address Book Entry</title>
<visible>1</visible>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
<objectClass id="mozillaOrgPerson"></objectClass>
</objectClasses>

<attributes>
<attribute id="givenName">
	<display>First Name</display>
	<onchange>=autoFill(cn;%sn% %givenName%)</onchange>
	<order>1</order>
</attribute>
<attribute id="sn">
	<display>Last Name</display>
	<onchange>=autoFill(cn;%sn% %givenName%)</onchange>
	<order>2</order>
</attribute>
<attribute id="cn">
	<display>Display Name</display>
	<order>3</order>
</attribute>
<attribute id="mozillaNickName">
	<display>NickName</display>
	<order>4</order>
	<spacer>1</spacer>
</attribute>
<attribute id="mail">
	<display>Email</display>
	<order>5</order>
</attribute>
<attribute id="mozillaSecondEmail">
	<display>Alternative Email</display>
	<order>6</order>
</attribute>
<attribute id="nsAIMid">
	<display>AIM Nick</display>
	<order>7</order>
</attribute>
<attribute id="mozillaUseHtmlMail">
	<display>HTML Email Format</display>
	<order>8</order>
	<spacer>1</spacer>
</attribute>
<attribute id="telephoneNumber">
	<display>Work Phone Number</display>
	<order>9</order>
</attribute>
<attribute id="homePhone">
	<display>Home Phone Number</display>
	<order>10</order>
</attribute>
<attribute id="facsimileTelephoneNumber">
	<display>Fax Number</display>
	<order>11</order>
</attribute>
<attribute id="pager">
	<display>Pager</display>
	<order>12</order>
</attribute>
<attribute id="mobile">
	<display>Mobile</display>
	<order>13</order>
	<spacer>1</spacer>
</attribute>
<attribute id="mozillaHomeStreet">
	<display>Address (personal)</display>
	<order>14</order>
</attribute>
<attribute id="mozillaHomeLocalityName">
	<display>City (personal)</display>
	<order>15</order>
</attribute>
<attribute id="mozillaHomeState">
	<display>State (personal)</display>
	<order>16</order>
</attribute>
<attribute id="mozillaHomePostalCode">
	<display>Zip (personal)</display>
	<order>17</order>
</attribute>
<attribute id="mozillaHomeCountryName">
	<display>Country (personal)</display>
	<order>18</order>
</attribute>
<attribute id="mozillaHomeUrl">
	<display>Web page (personal)</display>
	<order>19</order>
	<spacer>1</spacer>
</attribute>
<attribute id="title">
	<display>Title (professional)</display>
	<order>20</order>
</attribute>
<attribute id="ou">
	<display>Department (professional)</display>
	<order>21</order>
</attribute>
<attribute id="o">
	<display>Organization (professional)</display>
	<order>22</order>
</attribute>
<attribute id="street">
	<display>Address (professional)</display>
	<order>23</order>
</attribute>
<attribute id="l">
	<display>City (professional)</display>
	<order>24</order>
</attribute>
<attribute id="st">
	<display>State (professional)</display>
	<order>25</order>
</attribute>
<attribute id="postalCode">
	<display>Zip (professional)</display>
	<order>26</order>
</attribute>
<attribute id="c">
	<display>Country (professional)</display>
	<order>27</order>
</attribute>
<attribute id="mozillaWorkUrl">
	<display>Web Page (professional)</display>
	<order>28</order>
	<spacer>1</spacer>
</attribute>
<attribute id="mozillaCustom1">
	<display>Custom 1</display>
	<order>29</order>
</attribute>
<attribute id="mozillaCustom2">
	<display>Custom 2</display>
	<order>30</order>
</attribute>
<attribute id="mozillaCustom3">
	<display>Custom 3</display>
	<order>31</order>
</attribute>
<attribute id="mozillaCustom4">
	<display>Custom 4</display>
	<order>32</order>
</attribute>
<attribute id="description">
	<display>Description</display>
	<order>33</order>
</attribute>
</attributes>

</template>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/ou.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<template>
<askcontainer>1</askcontainer>
<description>New Organisational Unit</description>
<icon>ldap-ou.png</icon>
<invalid>0</invalid>
<rdn>ou</rdn>
<!-- <regexp>^o=.*,</regexp> -->
<title>Generic: Organisational Unit</title>
<visible>1</visible>

<objectClasses>
<objectClass id="organizationalUnit"></objectClass>
</objectClasses>

<attributes>
<attribute id="ou">
	<display>Organisational Unit</display>
	<hint>don't include "ou="</hint>
	<order>1</order>
	<page>1</page>
</attribute>
</attributes>

</template>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/sambaSamAccount.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<template>
<askcontainer>1</askcontainer>
<description>New Samba3 Account</description>
<icon>ldap-user.png</icon>
<invalid>0</invalid>
<rdn>cn</rdn>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<title>Samba: Account</title>
<visible>1</visible>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
<objectClass id="sambaSAMAccount"></objectClass>
<objectClass id="posixAccount"></objectClass>
</objectClasses>

<attributes>
<attribute id="givenName">
	<display>First name</display>
	<icon>ldap-uid.png</icon>
	<onchange>=autoFill(cn;%givenName% %sn%)</onchange>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sn">
	<display>Last name</display>
	<onchange>=autoFill(cn;%givenName% %sn%)</onchange>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="cn">
	<display>Common Name</display>
	<order>3</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="gidNumber">
	<display>GID Number</display>
	<onchange>=autoFill(homeDirectory;/home/users/%gidNumber|0-0/T%/%uid|3-%)</onchange>
	<onchange>=autoFill(uid;%gidNumber|0-0/T%-%givenName|0-1/l%%sn/l%)</onchange>
	<order>4</order>
	<page>1</page>
	<value><![CDATA[=php.PickList(/;(&(objectClass=posixGroup));gidNumber;%cn%;;;;cn)]]></value>
</attribute>
<attribute id="uid">
	<display>User ID</display>
	<onchange>=autoFill(homeDirectory;/home/users/%gidNumber|0-0/T%/%uid|3-%)</onchange>
	<order>5</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="uidNumber">
	<display>UID Number</display>
	<order>6</order>
	<page>1</page>
	<readonly>1</readonly>
	<value>=php.GetNextNumber(/;uidNumber)</value>
</attribute>
<attribute id="sambaSID">
	<display>Samba SID</display>
	<helper>
		<id>sidsuffix</id>
		<value>=php.GetNextNumber(/;uidNumber;false;;*2,+1000)</value>
	</helper>
	<order>7</order>
	<page>1</page>
	<post>=php.Join(-;%sambaSID%,%sidsuffix%)</post>
	<spacer>1</spacer>
	<value><![CDATA[=php.PickList(/;(&(objectClass=sambaDomain));sambaSID;%sambaSID% (%sambaDomainName%);;;;sambaDomainName)]]></value>
</attribute>
<attribute id="userPassword">
	<display>Password</display>
	<icon>lock.png</icon>
	<onchange>=autoFill(sambaLMPassword;%userPassword%)</onchange>
	<onchange>=autoFill(sambaNTPassword;%userPassword%)</onchange>
	<order>8</order>
	<post>=php.PasswordEncrypt(%enc%;%userPassword%)</post>
	<page>1</page>
	<verify>1</verify>
</attribute>
<attribute id="sambaLMPassword">
	<display>LM Password</display>
	<order>9</order>
	<page>1</page>
	<post>=php.PasswordEncrypt(LM;%sambaLMPassword%)</post>
	<type>password</type>
</attribute>
<attribute id="sambaNTPassword">
	<display>NT Password</display>
	<order>10</order>
	<page>1</page>
	<post>=php.PasswordEncrypt(NT;%sambaNTPassword%)</post>
	<spacer>1</spacer>
	<type>password</type>
</attribute>
<attribute id="loginShell">
	<display>Login shell</display>
	<icon>terminal.png</icon>
	<order>11</order>
	<page>1</page>
	<type>select</type>
	<!-- <value><![CDATA[=php.PickList(/;(&(objectClass=posixAccount));loginShell;%loginShell%)]]></value> -->
	<value id="/bin/sh">/bin/sh</value>
	<value id="/bin/csh">/bin/csh</value>
	<value id="/bin/tsh">/bin/tsh</value>
</attribute>
<attribute id="sambaPrimaryGroupSID">
	<display>Primary Group ID</display>
	<helper>
		<id>sidpgsuffix</id>
		<value></value>
	</helper>
	<order>13</order>
	<page>1</page>
	<post>=php.Join(-;%sambaPrimaryGroupSID%,%sidpgsuffix%)</post>
	<spacer>1</spacer>
	<value><![CDATA[=php.PickList(/;(&(objectClass=sambaGroupMapping));sambaSID;%sambaSID% (%cn%);sambaPrimaryGroupSID;;;;cn)]]></value>
</attribute>
<attribute id="homeDirectory">
	<display>Home directory</display>
	<order>14</order>
	<page>1</page>
</attribute>
<attribute id="sambaAcctFlags">
	<hidden>1</hidden>
	<value>[U]</value>
</attribute>
</attributes>

</template>

=== PacktPublishing/PHP-8-Programming-Tips-Tricks-and-Best-Practices/sample_data/phpldapadmin-1.2.3/templates/creation/courierMailAccount.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE template SYSTEM "template.dtd">

<template>
<askcontainer>1</askcontainer>
<description>New Courier Mail Account</description>
<icon>mail_account.png</icon>
<invalid>0</invalid>
<rdn>cn</rdn>
<!--<regexp>^ou=People,o=.*,</regexp>-->
<title>Courier Mail: Account</title>
<visible>1</visible>

<objectClasses>
<objectClass id="inetOrgPerson"></objectClass>
<objectClass id="courierMailAccount"></objectClass>
</objectClasses>

<attributes>
<attribute id="givenName">
	<display>Given Name</display>
	<onchange>=autoFill(cn;%givenName% %sn%)</onchange>
	<onchange>=autoFill(uid;%gidNumber|0-0/T%-%givenName|0-1/l%%sn/l%)</onchange>
	<order>1</order>
	<page>1</page>
</attribute>
<attribute id="sn">
	<display>Last name</display>
	<onchange>=autoFill(cn;%givenName% %sn%)</onchange>
	<onchange>=autoFill(uid;%gidNumber|0-0/T%-%givenName|0-1/l%%sn/l%)</onchange>
	<order>2</order>
	<page>1</page>
</attribute>
<attribute id="cn">
	<display>Common Name</display>
	<order>3</order>
	<page>1</page>
	<spacer>1</spacer>
</attribute>
<attribute id="uid">
	<display>User ID</display>
	<icon>ldap-uid.png</icon>
	<!--<onchange>=autoFill(homeDirectory;/home/users/%uid%)</onchange>-->
	<onchange>=autoFill(homeDirectory;/home/users/%gidNumber|0-0/T%/%uid|3-%)</onchange>
	<order>4</order>
	<page>1</page>
</attribute>
<attribute id="uidNumber">
	<display>UID Number</display>
	<icon>terminal.png</icon>
	<order>6</order>
	<page>1</page>
	<readonly>1</readonly>
	<value>=php.GetNextNumber(/;uidNumber)</value>
</attribute>
<attribute id="gidNumber">
	<display>GID Number</display>
	<onchange>=autoFill(uid;%gidNumber|0-0/T%-%givenName|0-1/l%%sn/l%)</onchange>
	<onchange>=autoFill(homeDirectory;/home/users/%gidNumber|0-0/T%/%uid|3-%)</onchange>
	<order>7</order>
	<page>1</page>
	<spacer>1</spacer>
	<value><![CDATA[=php.PickList(/;(&(objectClass=posixGroup));gidNumber;%cn%;;;;cn)]]></value>
</attribute>
<attribute id="homeDirectory">
	<display>Home Directory</display>
	<order>8</order>
	<page>1</page>
</attribute>
<attribute id="mail">
	<display>Email</display>
	<icon>mail.png</icon>
	<order>9</order>
	<page>1</page>
</attribute>
<attribute id="mailbox">
	<display>Mailbox</display>
	<order>10</order>
	<page>1</page>
</attribute>
<attribute id="userPassword">
	<display>Password</display>
	<icon>lock.png</icon>
	<order>11</order>
	<page>1</page>
	<post>=php.PasswordEncrypt(%enc%;%userPassword%)</post>
	<verify>1</verify>
</attribute>
</attributes>

</template>
